spring:
  security:
    user:
      name: hongyeongjune
      password: hongyeongjune
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security?verifyServerCertificate=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: ruathsgkwk0!
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 443
  ssl:
    enabled: true
    key-store: src/main/resources/bootsecurity.p12
    key-store-password: ruathsgkwk0!
    key-store-type: PKCS12
    key-alias: bootsecurity